# Generated by Django 4.0.1 on 2022-01-05 17:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triple_id', models.CharField(max_length=12)),
                ('station_name', models.CharField(max_length=200)),
                ('station_id', models.CharField(max_length=10)),
                ('state_code', models.CharField(max_length=2)),
                ('state_name', models.CharField(max_length=100)),
                ('network_code', models.CharField(max_length=20)),
                ('network_name', models.CharField(max_length=50)),
                ('elevation', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('county_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
