# Generated by Django 4.0.1 on 2022-01-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stations',
            new_name='Station',
        ),
    ]
